version: '3.8'

services:
  node:
    build: 
      context: ./
      dockerfile: docker/node/Dockerfile
    env_file: ./.env
    depends_on:
      - mysql
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=${DATABASE_URL}
  mysql:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  mysql:
  node_modules: